//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF5Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeekReportEntities : DbContext
    {
        public WeekReportEntities()
            : base("name=WeekReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_CarAssRe> TB_CarAssRe { get; set; }
        public DbSet<TB_DeInfo> TB_DeInfo { get; set; }
        public DbSet<TB_HumanRe> TB_HumanRe { get; set; }
        public DbSet<TB_InsurenceRe> TB_InsurenceRe { get; set; }
        public DbSet<TB_MonthGoal> TB_MonthGoal { get; set; }
        public DbSet<TB_OldCarSaleRe> TB_OldCarSaleRe { get; set; }
        public DbSet<TB_OrderReport> TB_OrderReport { get; set; }
        public DbSet<TB_Report> TB_Report { get; set; }
        public DbSet<TB_User> TB_User { get; set; }
    }
}
