//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CarAssRe
    {
        public string CarAssReID { get; set; }
        public Nullable<int> RefinementNum { get; set; }
        public Nullable<int> VAudioNum { get; set; }
        public string RefineDetail { get; set; }
        public Nullable<int> AssProNum { get; set; }
        public Nullable<int> PDSProNum { get; set; }
        public string OthersProDetail { get; set; }
        public Nullable<int> SelfNumber { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DeInfo
    {
        public int sid { get; set; }
        public string dep { get; set; }
        public string fatherdep { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HumanRe
    {
        public string HumanResourceReID { get; set; }
        public Nullable<int> PeopleNeed { get; set; }
        public Nullable<int> Interview { get; set; }
        public string NewEmpDetail { get; set; }
        public string SpecialEmp { get; set; }
        public string WeekGoodEmp { get; set; }
        public Nullable<int> SelfNumber { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_InsurenceRe
    {
        public string InsurenceID { get; set; }
        public Nullable<int> InGoal { get; set; }
        public Nullable<int> AnyCaseToNow { get; set; }
        public Nullable<int> CarBdCaseToNow { get; set; }
        public Nullable<int> MoneyToNow { get; set; }
        public Nullable<int> InSecCon { get; set; }
        public Nullable<int> CarBdSec { get; set; }
        public Nullable<int> AnyCaseSec { get; set; }
        public Nullable<int> WeekTotalBd { get; set; }
        public Nullable<int> MonTotalExR { get; set; }
        public Nullable<int> MonAnyExR { get; set; }
        public Nullable<int> MonBdExR { get; set; }
        public string RefinProject { get; set; }
        public Nullable<int> TotalWeekImport { get; set; }
        public Nullable<int> SelfNumber { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MonthGoal
    {
        public int sid { get; set; }
        public string Bureau { get; set; }
        public int Class { get; set; }
        public int yyyy { get; set; }
        public int mm { get; set; }
        public Nullable<int> InGoalNum { get; set; }
        public Nullable<int> InAny { get; set; }
        public Nullable<int> InBd { get; set; }
        public Nullable<int> OrderNum { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OldCarSaleRe
    {
        public string OldCarSaleReID { get; set; }
        public Nullable<int> ChangeBuy { get; set; }
        public Nullable<int> BuyEx { get; set; }
        public Nullable<int> DealNum { get; set; }
        public string FailDealDetail { get; set; }
        public Nullable<int> SelfNumber { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OrderReport
    {
        public string OrderReID { get; set; }
        public Nullable<int> MonthGoal { get; set; }
        public Nullable<int> OrderedCount { get; set; }
        public Nullable<int> SaleCount { get; set; }
        public Nullable<int> OnControl { get; set; }
        public Nullable<int> Expectations { get; set; }
        public string OrderDetail { get; set; }
        public string UnorderDetail { get; set; }
        public string WeekCar { get; set; }
        public string Others { get; set; }
        public Nullable<int> SelfNumber { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Report
    {
        public int ReportID { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string LastEditor { get; set; }
        public string Writer { get; set; }
        public string Bureau { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<bool> GoalStatus { get; set; }
        public string OrderReID { get; set; }
        public string InsurenceReID { get; set; }
        public string OldCarSaleReID { get; set; }
        public string CarAssReID { get; set; }
        public string HumanManageReID { get; set; }
        public string L2Comment { get; set; }
        public string L3Comment { get; set; }
    }
}
namespace EF5Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_User
    {
        public string Acc { get; set; }
        public string Bureau { get; set; }
        public Nullable<int> Class { get; set; }
        public string pass { get; set; }
        public Nullable<int> lv { get; set; }
        public Nullable<bool> edit { get; set; }
        public Nullable<bool> deleteable { get; set; }
        public Nullable<bool> write { get; set; }
        public string name { get; set; }
    }
}
